apiVersion: v1
kind: ConfigMap
metadata:
  name: wellnesshub-config
  namespace: wellnesshub
data:
  POSTGRES_PORT: "5432"
  ADMIN_DB: WellnessHubAdmin
  EXPERT_DB: WellnessHubbase
  ENTREPRISE_X_DB: EntrepriseXdb
  ENTREPRISE_Y_DB: EntrepriseYdb
  EUREKA_PORT: "8761"
  EUREKA_URL: "http://eureka-service:8761/eureka/"
  # Remplacer par l'IP ou le domaine de votre VM / cluster
  VITE_API_URL: "http://YOUR_VM_IP:8762/api"
